version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - repo
    - repo1
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'tekton-multi-repo-e2e-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_url: 'https://github.com/idsb3t1/KEEP-pipeline-tests-resources'
      type: link
      has_issues: false
  repo1:
    service_id: githubpublic
    parameters:
      repo_url: 'https://github.com/idsb3t1/KEEP-1-pipeline-tests-resources'
      type: link
      has_issues: false
  repo2:
    service_id: githubpublic
    parameters:
      repo_url: 'https://github.com/idsb3t1/KEEP-2-pipeline-tests-resources'
      type: link
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
        - repo1
        - repo2
      name: 'multi-repo-pipeline'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          GIT_REPO_1: repo1
          GIT_REPO_2: repo2
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          REPOSITORY: '{{services.repo.parameters.repo_url}}'
          REVISION: hello-containers_master
        execute: true
form:
  pipeline:
    parameters:
      app-name: 'multi-repo-1-{{timestamp}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
