version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'Tekton-Toolchain-Triggers-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'Tekton-Github-Triggers-{{timestamp}}'
      source_repo_url: 'https://github.com/ziheng-c/greenwell-tekton'
      type: clone
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          REVISION: master
          GIT_NAME: 'Tekton-Github-Triggers-{{timestamp}}'
        execute: true
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
